"""
Django settings for cbers4a project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'qqcoisa')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition
# pip install django-process
"""
./process/management/commands/_actions.py:
DE
        'project_path': settings.BASE_DIR,

PARA
        'project_path': str(settings.BASE_DIR),
.proccess/models.py
DE
    description = models.CharField(_("description"), max_length=500, unique=True)
PARA
    description = models.CharField(_("description"), max_length=5000, unique=True)
DE
    raise ValidationError({'status': _(f'status requested {status} not in status choices')})
PARA
    raise ValidationError({'status': _(f'status requested {self.status} not in status choices')})

"""
INSTALLED_APPS = [
    'process.apps.ProcessConfig',
    'cbers4amanager.apps.Cbers4AmanagerConfig',
    'django.contrib.gis',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cbers4a.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cbers4a.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ['POST_DB'],
        'USER': os.environ['POST_USER'],
        'PASSWORD': os.environ['POST_PASSWORD'],
        'HOST': os.environ['POST_HOST'],
        'PORT': '5432'
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Manaus'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = BASE_DIR / 'uploads/'
MEDIA_URL = '/uploads/'

#https://github.com/ui/django-thumbnails
THUMBNAILS = {
    'METADATA': {
        'BACKEND': 'thumbnails.backends.metadata.DatabaseBackend',
    },
    'STORAGE': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    
    'SIZES': {
        'small': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 40, 'height': 40},
                #{'PATH': 'thumbnails.processors.crop', 'width': 80, 'height': 80},
                #{'PATH': 'thumbnails.processors.flip', 'direction': 'horizontal'}
            ],
            'POST_PROCESSORS': [
                {
                    'PATH': 'thumbnails.post_processors.optimize',
                    'png_command': 'optipng -force -o7 "%(filename)s"',
                    'jpg_command': 'jpegoptim -f --strip-all "%(filename)s"',
                },
            ],
        },
        'large': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 100, 'height': 100},
            ],
        },
        'watermarked': {
            'PROCESSORS': [
                {'PATH': 'thumbnails.processors.resize', 'width': 20, 'height': 20},
                # Only supports PNG. File must be of the same size with thumbnail (20 x 20 in this case)
                {'PATH': 'thumbnails.processors.add_watermark', 'watermark_path': 'watermark.png'}
            ],
        }
    }
}

FILE_UPLOAD_PERMISSIONS = 0o775
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o775

CBERS4AMANAGER = {
    'LIMITS': {
        'max_storage':'1T',
        'min_area_com_dados_percent':'45.0',
        'max_area_nuvens_percent':'20.0',
    },
    'SAMPLE_FOLDER': 'cbers4amanager/static/cbers4amanager/amostras'
}

# Avoid exception SuspiciousOperation[TooManyFieldsSent]
# at /admin/process/job/ when deleting more than 1000 rows
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

######### CASO Tentando rodar sem Docker, diretamente no SO, deve-se #########
### Conf BANCO PostgreSQL: 
#  ip a # Alterar as variáveis de ambiente para apontar para este servidor --> POST_HOST 
#  apt install postgresql postgis
#  su postgres # # Alterar as variáveis de ambiente com este username --> POST_USER
#  psql
#  postgres=# \password -- # Alterar as variáveis de ambiente com esta senha -> POST_PASSWORD
#  postgres=# CREATE DATABASE cbers4a;
#  postgres=# \c cbers4a
#  cbers4a=# CREATE EXTENSION postgis; 
#  cbers4a=# CREATE EXTENSION postgis_raster;
#  cbers4a=# CREATE EXTENSION postgis_sfcgal; 
### Conf APP Django-Cbers4amanager:
#  pip install django psycopg2 requests

# Setar as variáveis de ambiente POST_USER, POST_PASSWORD e POST_HOST, Path, PYTHONHOME e OSGEO4W_ROOT
# Path, PYTHONHOME e OSGEO4W_ROOT --> utilizar uma instalação do QGIS, executar no terminal
# (alterar de acordo com a versão do QGIS):
# PS > $env:Path += ';C:\Program Files\QGIS 3.22.5\bin;C:\Program Files\QGIS 3.22.5\apps\Python39;C:\Program Files\QGIS 3.22.5\apps\Python39\Scripts\;C:\Program Files\QGIS 3.22.5\apps\Python39\Lib'
# PS > $env:PYTHONHOME = r'C:\Program Files\QGIS 3.22.5\apps\Python39'
# PS > $env:OSGEO4W_ROOT = r'C:\Program Files\QGIS 3.22.5'
# Encontrar o arquivo libgdal (QGIS) e descomentar abaixo
#GDAL_LIBRARY_PATH = r'C:\Program Files\QGIS 3.22.5\bin\gdal304.dll'

# CASO:
# GDAL_ERROR 1: b'PROJ: proj_create_from_database: 
# C:\\Program Files\\PostgreSQL\\14\\share\\contrib\\postgis-3.2\\proj\\proj.db 
# contains DATABASE.LAYOUT.VERSION.MINOR = 0 whereas a number >= 2 is expected. 
# It comes from another PROJ installation.' 
# SOLUÇÃO, descomentar abaixo (alterar de acordo com a versão do QGIS):
#os.environ['PROJ_LIB'] = r'C:\Program Files\QGIS 3.22.5\share\proj'

# CASO:
# ImportError: Could not find the GEOS library (tried "geos_c", "libgeos_c-1"). 
# Try setting GEOS_LIBRARY_PATH in your settings.
# SOLUÇÃO, descomentar abaixo (alterar de acordo com a versão do QGIS):
#os.environ['GEOS_LIBRARY_PATH'] = r'C:\Program Files\QGIS 3.22.5\bin\geos_c.dll'
#################################################################################