# Generated by Django 4.0.3 on 2022-04-11 19:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicaoRGB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rgb', models.FilePathField(blank=True, null=True, path='/home/capdiego/Documents/cbers4a/uploads/rgb')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('nome', models.CharField(blank=True, max_length=500, null=True)),
                ('nome_base', models.CharField(blank=True, max_length=500, null=True)),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('finalizado', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='INOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inom', models.CharField(max_length=20)),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='INOMClippered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobertura_nuvens', models.FloatField(blank=True, default=1, null=True)),
                ('pronto_para_pansharppen', models.BooleanField(blank=True, default=False, null=True)),
                ('inom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbers4amanager.inom')),
                ('pancromatica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbers4amanager.download')),
                ('rgb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbers4amanager.composicaorgb')),
            ],
        ),
        migrations.CreateModel(
            name='Pansharpened',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pansharp', models.FilePathField(blank=True, null=True, path='/home/capdiego/Documents/cbers4a/uploads/pansharp')),
                ('insumos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbers4amanager.inomclippered')),
            ],
        ),
        migrations.AddField(
            model_name='composicaorgb',
            name='blue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set', to='cbers4amanager.download'),
        ),
        migrations.AddField(
            model_name='composicaorgb',
            name='green',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='green', to='cbers4amanager.download'),
        ),
        migrations.AddField(
            model_name='composicaorgb',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red', to='cbers4amanager.download'),
        ),
    ]
