# Generated by Django 4.0.3 on 2022-04-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
