# Generated by Django 4.0.3 on 2022-04-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0002_alter_download_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='inom',
            name='inom',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
