# Generated by Django 4.0.3 on 2022-04-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0004_download_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='content_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='iniciado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='terminado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
