# Generated by Django 4.0.3 on 2022-04-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0005_download_content_length_download_iniciado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='progresso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
