# Generated by Django 4.0.2 on 2022-04-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0007_alter_download_content_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composicaorgb',
            options={'verbose_name': '2) Composição RGB'},
        ),
        migrations.AlterModelOptions(
            name='download',
            options={'verbose_name': '1) Download'},
        ),
        migrations.AlterModelOptions(
            name='inom',
            options={'verbose_name_plural': '0) Área de Interesse'},
        ),
        migrations.AlterModelOptions(
            name='inomclippered',
            options={'verbose_name': '3) Recortes RGB/PAN'},
        ),
        migrations.AlterModelOptions(
            name='pansharpened',
            options={'verbose_name': '4) Fusão RGB/PAN'},
        ),
        migrations.AlterField(
            model_name='composicaorgb',
            name='rgb',
            field=models.FilePathField(blank=True, null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/rgb'),
        ),
        migrations.AlterField(
            model_name='download',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='bandas/'),
        ),
        migrations.AlterField(
            model_name='pansharpened',
            name='pansharp',
            field=models.FilePathField(blank=True, null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/pansharp'),
        ),
    ]
