# Generated by Django 4.0.2 on 2022-04-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0009_alter_composicaorgb_options_composicaorgb_finalizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composicaorgb',
            options={'verbose_name': 'Composição RGB', 'verbose_name_plural': '2) Composições RGB'},
        ),
        migrations.AlterModelOptions(
            name='download',
            options={'verbose_name': 'Download', 'verbose_name_plural': '1) Downloads'},
        ),
        migrations.AlterModelOptions(
            name='inom',
            options={'verbose_name': 'Área de Interesse', 'verbose_name_plural': '0) Áreas de Interesse'},
        ),
        migrations.AlterModelOptions(
            name='inomclippered',
            options={'verbose_name': 'Recorte RGB/PAN', 'verbose_name_plural': '3) Recortes RGB/PAN'},
        ),
        migrations.AlterModelOptions(
            name='pansharpened',
            options={'verbose_name': 'Fusão RGB/PAN', 'verbose_name_plural': '4) Fusão RGB/PAN'},
        ),
        migrations.AlterField(
            model_name='composicaorgb',
            name='rgb',
            field=models.FilePathField(blank=True, match='*RGB*', null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/rgb'),
        ),
    ]
