# Generated by Django 4.0.2 on 2022-04-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0010_alter_composicaorgb_options_alter_download_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inom',
            name='mi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mapa Índice'),
        ),
        migrations.AlterField(
            model_name='composicaorgb',
            name='rgb',
            field=models.FilePathField(blank=True, help_text='Este arquivo será criado após escolher a opção "Começar composição das linhas selecionadas".', match='(.*)RGB.tif', null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/rgb'),
        ),
    ]
