# Generated by Django 4.0.2 on 2022-04-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0011_inom_mi_alter_composicaorgb_rgb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inomclippered',
            old_name='pronto_para_pansharppen',
            new_name='finalizado',
        ),
    ]
