# Generated by Django 4.0.2 on 2022-04-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0012_rename_pronto_para_pansharppen_inomclippered_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicaorgb',
            name='nome_base',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
