# Generated by Django 4.0.2 on 2022-04-15 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0013_composicaorgb_nome_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='inomclippered',
            name='nome',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inomclippered',
            name='recorte_pancromatica',
            field=models.FilePathField(blank=True, help_text='Este arquivo será criado após escolher a opção "Começar recorte PAN das linhas selecionadas".', match='(.*)RGB.tif', null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/recortes'),
        ),
        migrations.AddField(
            model_name='inomclippered',
            name='recorte_rgb',
            field=models.FilePathField(blank=True, help_text='Este arquivo será criado após escolher a opção "Começar recorte RGB das linhas selecionadas".', match='(.*)RGB.tif', null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/recortes'),
        ),
        migrations.AlterField(
            model_name='composicaorgb',
            name='nome_base',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='composicaorgb',
            name='rgb',
            field=models.FilePathField(blank=True, help_text='Este arquivo será criado após escolher a opção "Começar composição das linhas selecionadas".', match='(.*)RGB.tif', null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/rgbs'),
        ),
        migrations.AlterField(
            model_name='inomclippered',
            name='pancromatica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbers4amanager.download', verbose_name='Pancromática'),
        ),
    ]
