# Generated by Django 4.0.2 on 2022-04-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0014_inomclippered_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inomclippered',
            name='nome',
            field=models.CharField(default='', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inomclippered',
            name='recorte_pancromatica',
            field=models.FilePathField(blank=True, help_text='Este arquivo será criado após escolher a opção "Começar recorte PAN das linhas selecionadas".', match='(.*)PAN.tif', max_length=300, null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/recortes'),
        ),
        migrations.AlterField(
            model_name='inomclippered',
            name='recorte_rgb',
            field=models.FilePathField(blank=True, help_text='Este arquivo será criado após escolher a opção "Começar recorte RGB das linhas selecionadas".', match='(.*)RGB.tif', max_length=300, null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/recortes'),
        ),
    ]
