# Generated by Django 4.0.2 on 2022-04-16 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0016_inomclippered_area_util'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inomclippered',
            name='area_util',
            field=models.FloatField(blank=True, help_text='Este dados será computado após escolher a opção "Começar recorte RGB das linhas selecionadas". Equivale ao "STATISTICS_VALID_PERCENT" mínimo entre as bandas RGB, obtido pelo comando gdalinfo.', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Área útil (%)'),
        ),
    ]
