# Generated by Django 4.0.2 on 2022-04-17 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0017_alter_inomclippered_area_util'),
    ]

    operations = [
        migrations.AddField(
            model_name='pansharpened',
            name='finalizado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='inomclippered',
            name='area_util',
            field=models.FloatField(blank=True, help_text='Este dado será computado após escolher a opção "Começar recorte RGB das linhas selecionadas". <br>Equivale ao "STATISTICS_VALID_PERCENT" mínimo entre as bandas do Recorte RGB, obtido pelo comando <i>gdalinfo recorte.tif -stats</i>.', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Área com dados (%)'),
        ),
        migrations.AlterField(
            model_name='inomclippered',
            name='cobertura_nuvens',
            field=models.FloatField(blank=True, help_text='Este dado será computado após escolher a opção "Começar recorte RGB das linhas selecionadas". <br>Equivale ao "STATISTICS_VALID_PERCENT" da classificação das nuvens, obtido pelo comando <i>gdalinfo nuvens.tif -stats</i>.', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Área de nuvens (%)'),
        ),
        migrations.AlterField(
            model_name='inomclippered',
            name='recorte_rgb',
            field=models.FilePathField(blank=True, help_text='Este arquivo será criado após escolher a opção "Começar recorte RGB das linhas selecionadas". ', match='(.*)RGB.tif', max_length=300, null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/recortes'),
        ),
    ]
