# Generated by Django 4.0.2 on 2022-04-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0020_alter_pansharpened_pansharp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicaorgb',
            name='rgb',
            field=models.FilePathField(blank=True, help_text='Este arquivo será criado após escolher a opção "Começar composição das linhas selecionadas".', match='(.*)RGB.tif', null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/rgbs'),
        ),
        migrations.AlterField(
            model_name='download',
            name='tipo',
            field=models.CharField(blank=True, choices=[('nir', 'Infravermelho Próximo'), ('red', 'Vermelho'), ('green', 'Verde'), ('blue', 'Azul'), ('pan', 'Pancromática'), ('', 'Indefinido')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='inomclippered',
            name='recorte_pancromatica',
            field=models.FilePathField(blank=True, help_text='Este arquivo será criado após escolher a opção "Começar recorte PAN das linhas selecionadas".', match='(.*)PAN.tif', max_length=300, null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/recortes'),
        ),
        migrations.AlterField(
            model_name='inomclippered',
            name='recorte_rgb',
            field=models.FilePathField(blank=True, help_text='Este arquivo será criado após escolher a opção "Começar recorte RGB das linhas selecionadas". ', match='(.*)RGB.tif', max_length=300, null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/recortes'),
        ),
        migrations.AlterField(
            model_name='pansharpened',
            name='pansharp',
            field=models.FilePathField(blank=True, help_text='Este arquivo será criado após escolher a opção "Começar Fusão RGB/PAN das linhas selecionadas". ', match='(.*).tif', max_length=300, null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/pansharp'),
        ),
    ]
