# Generated by Django 4.0.2 on 2022-04-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0021_alter_composicaorgb_rgb_alter_download_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='progresso',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
