# Generated by Django 4.0.2 on 2022-04-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0022_alter_download_progresso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='arquivo',
            field=models.FilePathField(blank=True, match='(.*).tif', null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/bandas'),
        ),
    ]
