# Generated by Django 4.0.3 on 2022-05-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0025_composicaorgb_bounds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inom',
            options={'verbose_name': 'Área de Interesse', 'verbose_name_plural': 'Áreas de Interesse'},
        ),
        migrations.AddField(
            model_name='inom',
            name='melhor_imagem',
            field=models.FilePathField(blank=True, match='(.*).tif', max_length=300, null=True, path='/home/capdiego/Documents/cbers4a/uploads/pansharp'),
        ),
    ]
