# Generated by Django 4.0.2 on 2022-04-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers4amanager', '0026_alter_composicaorgb_rgb_alter_download_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='arquivo',
            field=models.FilePathField(blank=True, null=True, path='/Users/humberto/Documents/DIEGO/cbers4a/uploads/bandas'),
        ),
    ]
